### ISSUE TITLE
Currently we don't align experiments.css behavior with webpack for the following reasons:50

### ISSUE THREAD

**Issue by CobraFighter** [prati0100/git-gui#105]
Currently we don't align experiments.css behavior with webpack for the following reasons:
* legacy browser support
* custom css module support

both these features can be supported by mini-css-extract-plugin with css-loader, so when we support mini-css-extract-plugin we should consider  align with webpack, which includes
* set experiments.css to `false` by default
* align css chunk loading and code generation logic with webpack

_Originally posted by @hardfist in https://github.com/web-infra-dev/rspack/issues/5096_

**Comment by prati0100** [comment]
This project has nothing to do with CSS or browser. This seems to have been opened in error. Closing.
