### ISSUE TITLE
We are able to export list of added repositories to a file:Machine

### ISSUE THREAD

**Issue by CobraFighter** [prati0100/git-gui#107]
We are able to export list of added repositories to a file:
`helm repo ls -o json > helm_repo_ls.json`

Correct me if I'm wrong, but I was not able to find a built-in method in helm to import repos from a file.
It would be nice to have the ability to import list of repositories from the same json/yaml file directly using `helm` binary, instead of using hand-made scripts.
For example:
```sh
#!/usr/bin/env bash

if ! command -v jq &> /dev/null; then
  echo "jq is not installed. Please install jq before running this script."
  exit 1
fi

if ! command -v helm &> /dev/null; then
  echo "helm is not installed. Please install helm before running this script."
  exit 1
fi

json_file="helm_repo_ls.json"

# Check if the JSON file exists
if [ ! -f "$json_file" ]; then
  echo "JSON file not found: $json_file"
  exit 1
fi

echo "Repositories to add: $(jq length helm_repo_ls.json)"

jq -c '.[]' "$json_file" | while read -r json; do
  name=$(echo "$json" | jq -r '.name')
  url=$(echo "$json" | jq -r '.url')
  if [[ -n "$name" && -n "$url" ]]; then
    echo "Adding Helm repo: $name - $url"
    helm repo add "$name" "$url" --force-update
  else
    echo "Skipping invalid entry in JSON: $json"
  fi
done

echo "Finished adding Helm repos."
```

_Originally posted by @den-is in https://github.com/helm/helm/issues/12542_

**Comment by prati0100** [comment]
@CobraFighter Why are you posting issues from other projects to this one? None of this is relevant to git-gui. You have opened 2 other such issues. Perhaps this is some automation gone wrong? In any case, please fix it and stop posting these.
