### ISSUE TITLE
Update the maintainer, make it clear that j6/git-gui is not am impostor

### ISSUE THREAD

**Issue by ilyagr** [prati0100/git-gui#111]
Judging by https://github.com/git/git/commits/master/git-gui, the development of git-gui moved to https://github.com/j6t/git-gui. It would be nice if you updated this fork to include https://github.com/j6t/git-gui/commit/83cf2847b0896bf0d25587e8d5b04d9681c85f8b to make it clear that the other fork is now official (assuming this is true), and/or added a note that you aren't planning to keep this fork synced (assuming you aren't).

**Comment by prati0100** [comment]
Yes, that is true. Let me archive this repo and point to j6t's repo.

**Comment by prati0100** [comment]
Updated with https://github.com/prati0100/git-gui/commit/ad55db7c6bdb49981fa600905798790d24919481. Thanks for bringing this to my attention.
