### ISSUE TITLE
gitk: Colors for merge commits diffs

### ISSUE THREAD

**Issue by johnjohndoe** [prati0100/git-gui#18]
I noticed that the colors for merge commits diff are not the same as for a regular commit diff.
I customized the colors (green, red) for the regular commit.

![Gitk preferences / Colors tab](https://user-images.githubusercontent.com/144518/69883232-7e9f7400-12d3-11ea-89bc-6472515b00f8.png)

# Merge commit diff example

![Merge commit diff example](https://user-images.githubusercontent.com/144518/69883126-12bd0b80-12d3-11ea-8834-263f0d6972e0.png)

# Regular commit diff example

![Regular commit diff example](https://user-images.githubusercontent.com/144518/69883120-0cc72a80-12d3-11ea-8d01-f08cac10fb7d.png)

I personally don't like the colors of the merge commit diff (red, blue). As far as I know they are not configurable. I would use the same colors as for the regular commit diff. What is your opinion?

**Comment by johnjohndoe** [comment]
Oh! I just realized that this is git-gui not gitk. Sorry! Is there a issue tracker for gitk?

**Comment by prati0100** [comment]
Same comment as in the other issue. Please contact Paul about this issue.
