### ISSUE TITLE
gitk: Flatten packages

### ISSUE THREAD

**Issue by johnjohndoe** [prati0100/git-gui#19]
In a project with nested folders or packages the path to a file can show up rather long in the bottom right window <enter-name-here>.

![gitk bottom right window](https://user-images.githubusercontent.com/144518/69883388-3f255780-12d4-11ea-987e-7b0056b7a831.png)

If this windows cannot take a lot of space due to screen restrictions then the long paths wrap as shown in the following screenshot:

![gitk bottom right window wrapped paths](https://user-images.githubusercontent.com/144518/69883429-69771500-12d4-11ea-9591-e67f2f3476db.png)

It would be convenient to have the possibility to switch on/off package flattening as it is supported by IDEs such as IntelliJ - shown in the screenshot:

![Flatten packages option in IntelliJ or Android Studio](https://user-images.githubusercontent.com/144518/69883500-bf4bbd00-12d4-11ea-85d2-184029f75e59.png)

**Comment by johnjohndoe** [comment]
Oh! I just realized that this is git-gui not gitk. Sorry! Is there a issue tracker for gitk?

**Comment by prati0100** [comment]
Not one I'm aware of. Gitk is maintained by Paul Mackerras \<paulus@ozlabs.org\> over at git://ozlabs.org/~paulus/gitk.git

You should try contacting him about this issue. I'll close the issue here.
