### ISSUE TITLE
Can't paste copied text after closing git gui

### ISSUE THREAD

**Issue by dorian-marchal** [prati0100/git-gui#23]
Text copied in git gui (Right click > Copy) can only be pasted while git gui is running.
Once it's closed, the copied  text is removed from the clipboard (i.e. pasting doesn't work).

Tested on Ubuntu 16.04 and 18.04.

Note: `gitk` suffers from the same issue.

**Comment by prati0100** [comment]
Thanks for reporting. I can reproduce the issue on my setup (running Fedora 30).

But I don't think this is a git-gui bug. Firstly, all git-gui does is call `tk_textCopy` on the diff body widget. `tk_textCopy` is implemented by Tcl/Tk and we don't have any hand in it.

Further, I can see this behavior present in Firefox too (as an example). So, looking around, it is actually a rather notorious bug. In fact, there is even a [Ubuntu wiki entry](https://wiki.ubuntu.com/ClipboardPersistence) about it.

So, you should report this bug to Tk instead.
