### ISSUE TITLE
Set focus on close button after push

### ISSUE THREAD

**Issue by AtomicNibble** [prati0100/git-gui#27]
When you push a branch with `Cntl + p` + `Enter` the close button is disabled during the push.

But once the push completes the close button has no focus, so you can't just press enter to close the window, meaning you must use the mouse.

Thanks.

**Comment by prati0100** [comment]
You can hit Escape to close the window. That should be just as convenient as hitting Enter IMO.

**Comment by AtomicNibble** [comment]
Don't work for me, tried on Ubuntu and Win10.
Version 0.21

**Comment by prati0100** [comment]
>Version 0.21

Is this the git-gui version? There has not yet been a release of git-gui with this feature, but if you install the git-gui version that ships with Git v2.25.0 you should see that feature.

**Comment by AtomicNibble** [comment]
Yep, that works thanks!
