### ISSUE TITLE
git-gui: "missing close-bracket" error while doing branch->reset

### ISSUE THREAD

**Issue by roblub** [prati0100/git-gui#28]
See https://bugs.debian.org/951081 for description of a bug I've just reported in debian.

(You might be also aware of https://bugs.debian.org/950597, 'git-gui "Show History Context" raises "Application Error"' which also might be related to recent changes in git gui).

**Comment by prati0100** [comment]
Hi @roblub,

Thanks for reporting. Can reproduce the bug. Fix coming soon.

**Comment by prati0100** [comment]
Patch posted at https://lore.kernel.org/git/20200217161056.10864-1-me@yadavpratyush.com/

Let me know if it doesn't fix the problem for you.

**Comment by prati0100** [comment]
Fixed in 63a58457e094c9c9bbf562b872009d32f1f88133
