### ISSUE TITLE
Garbled output when typing "git gui" in PowerShell 6 with posh-git

### ISSUE THREAD

**Issue by patrikhuber** [prati0100/git-gui#34]
Hi,

@dahlbyk advised that this might likely be a bug in git-gui. I initially posted this in the posh-git repo, https://github.com/dahlbyk/posh-git/issues/738. This also got linked as potentially related https://github.com/microsoft/terminal/issues/4809.

Original bug report below.

Thank you!

### System Details

- posh-git version/path: 1.0.0 beta3 ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 6.2.4
- git version 2.25.0.windows.1
- OS: Microsoft Windows NT 10.0.18362.0

### Issue Description

posh-git seems to work fine overall. However when typing `git gui`, the git gui window opens, but on the powershell prompt, the encoding of the characters is outputted and the cursor stays on that line. Only after pressing "Enter", the prompt becomes "normal" again.

```
~\MyProj [mybranch +2 ~2 -0 !]> git gui    <-- nicely colourised
~\MyProj [93m[[0m[96mmybranch[0m[31m[49m +2[0m[31m[49m ~2[0m[31m[49m -0[0m[31m ![0m[93m][0m>    <-- no colours, "weird" output. Have to press "enter" to get prompt to normal again.
~\MyProj [mybranch +2 ~2 -0 !]>    <-- nicely colourised
```

![image](https://user-images.githubusercontent.com/4967343/74587540-ab6a4a00-4feb-11ea-93fb-99cadce54d23.png)

**Comment by prati0100** [comment]
Thanks for reporting. Unfortunately I don't use Windows so I can't really say why this happens.

Looking at the microsoft/terminal bug report, I understand that this is apparently not a git-gui specific issue, but a cygwin issue instead. If so, I think this issue should be closed.

**Comment by patrikhuber** [comment]
Thanks for the reply @prati0100. Anyone working on Windows or who develops and tests the Windows builds...?

Thanks.

**Comment by neilrees** [comment]
Potential solution?
https://github.com/microsoft/terminal/issues/4809#issuecomment-596249509

**Comment by prati0100** [comment]
As far as I understand, this is a problem with cygwin, not git-gui itself so I'm closing this issue. Please feel free to reopen it if you feel otherwise.
