### ISSUE TITLE
Want new feature: Allow translation

### ISSUE THREAD

**Issue by qiancy98** [prati0100/git-gui#37]
As you know, I'm a Chinese and everytime I have to first translate the items and then choose. I wonder if you can provide a place for localization, where we can translate the texts and submit. (Otherwise it takes a lot of time for me to translate the texts each time.)
Then we will have a localized program!

**Comment by prati0100** [comment]
Hi,

We already have localization and in fact, we also have a Chinese translation. You can use git-gui in Chinese by setting the environment variable `LANG` to `zh_CN`. For example, you can do:

```
LANG=zh_CN git gui
```

For more information, you can see [this](https://stackoverflow.com/questions/1427785/how-to-set-desired-language-in-git-gui).

The translation might be outdated. If you think you can improve them, I would be happy to accept updated translations. Please see the README for instructions to how you can contribute to the project.

**Comment by qiancy98** [comment]
Thank you!
