### ISSUE TITLE
Wrong character encoding in push window

### ISSUE THREAD

**Issue by nE0sIghT** [prati0100/git-gui#68]
My environment is `LANG=ru_RU.UTF-8`.  
Gui respect UTF-8 character encoding everywhere except terminal log while pushing new commits.

Here is screenshot:
![image](https://user-images.githubusercontent.com/3389586/140733529-a4882948-566d-4260-9f9a-0c6b3fa155fe.png)

And same action from terminal:
![image](https://user-images.githubusercontent.com/3389586/140733669-3a84e521-b0ef-4186-96e2-cac9466b3579.png)

Can it be configured to properly show UTF-8 text in push window?

**Comment by dalexeev** [comment]
* Fixed by https://github.com/j6t/git-gui/pull/6.
